### PR TITLE
fix: update deps

### PR DESCRIPTION
**Pull request by JiuRanYa**
Hi, iconify-json update some icon's set, could u pls update the version and release this pkg?

### CODE REVIEW

**Comment by hyoban** [comment]
Hi, if you want, you can help me update all the dependencies and submit the lock file to git.

**Comment by JiuRanYa** [comment]
@hyoban Sure, I have updated all the deps.

**Comment by hyoban** [comment]
Thanks! Can you commit the lock file update? Just run `pnpm install` locally then you can see it.

**Comment by JiuRanYa** [comment]
Seems the error from  pnpm version

**Pull request merged**
